In [56]:
# Name: Aditi M. Chavan
# Panel 2
# PB 54
# Topic: KNN Classifier
# Date: 13/08/20

In [44]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.neighbors import KNeighborsClassifier

In [45]:
dataset = pd.read_csv("C:\\Users\\Aditi\\Desktop\\ML\\knn.csv")

In [46]:
x = dataset.iloc[:,:-1].values
print(x)

[[2 4]
 [4 6]
 [4 4]
 [4 2]
 [6 4]
 [6 2]]


In [47]:
y = dataset.iloc[:,2].values
print(y)

['N' 'N' 'P' 'N' 'N' 'P']


In [48]:
classifier = KNeighborsClassifier(n_neighbors=3) #k=3
classifier.fit(x,y) #training

x_test = np.array([4,2])

y_predict = classifier.predict(x) #testing
print(y_predict)

from sklearn.metrics import confusion_matrix
confusion_matrix(y,y_predict)

['N' 'N' 'N' 'P' 'P' 'N']


array([[2, 2],
       [2, 0]], dtype=int64)

In [49]:
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
# Second Feature
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

# Label or target varible
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [50]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
weather_encoded = le.fit_transform(weather) #convert weather string labels into nos
print(weather_encoded)

temp_encoded = le.fit_transform(temp) #convert temp string labels into nos

label = le.fit_transform(play) #convert play string labels into nos

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [51]:
features = list(zip(weather_encoded, temp_encoded)) #combine weather & temp into single listof tuples

In [52]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)
model.fit(features,label) #train model using training dataset
predicted = model.predict([[0,2]]) #0:overcast 2:mild
print(predicted)

[1]


In [53]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.neighbors import KNeighborsRegressor

dataset = pd.read_csv("C:\\Users\\Aditi\\Desktop\\ML\\knn1.csv")

x = dataset.iloc[:,:-1].values
print(x)
y = dataset.iloc[:,2].values
print(y)

[[ 5.   45.  ]
 [ 5.11 26.  ]
 [ 5.6  30.  ]
 [ 5.9  34.  ]
 [ 4.8  40.  ]
 [ 5.8  36.  ]
 [ 5.3  19.  ]
 [ 5.8  28.  ]
 [ 5.5  23.  ]
 [ 5.6  32.  ]]
[77 47 55 59 72 60 40 60 45 58]


In [54]:
classifier = KNeighborsRegressor(n_neighbors=5) #k=5
classifier.fit(x,y) #training
x_test = np.array([5.50,26])
y_predict = classifier.predict([x_test]) #testing
print(y_predict)

[53.]


In [55]:
from sklearn.metrics import r2_score #r2_score used for KNeighborsRegressor

y_predict = classifier.predict(x)
r2_score(y, y_predict) #displays accuracy



0.679081158685922